name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
env:
  NODE_VERSION: 16

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: cd api && yarn install --frozen-lockfile

      - name: Code Linting
        run: cd api && yarn format:check
